spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&zeroDateTimeBehavior=convertToNull
    username: test
    password: test

logging:
  level:
    io.ebean: debug
    io.ebean.TXN: debug
    io.ebean.SQL: debug
